application: gae101chatex
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: django
  version: 1.3

inbound_services:
- channel_presence

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
